# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"

# Active Config
# command:
# scss-lint --format=Config shared/scss/wd-*.scss;
# ... will display linters that get caught.
# Working backwards from that config helps specify what is needed
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:
  FinalNewline:
    enabled: false

  NameFormat:
    enabled: false

  StringQuotes:
    enabled: false

  BangFormat:
    enabled: false

  BorderZero:
    enabled: false

  ColorKeyword:
    enabled: false

  Comment:
    enabled: false

  DeclarationOrder:
    enabled: false

  DuplicateProperty:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false

  EmptyRule:
    enabled: false

  HexLength:
    enabled: false

  HexNotation:
    enabled: false

  IdWithExtraneousSelector:
    enabled: false

  Indentation:
    enabled: false

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: false

  NestingDepth:
    enabled: false

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: false

  SingleLinePerProperty:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  SpaceAfterComma:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: false

  SpaceBeforeBrace:
    enabled: false

  SpaceBetweenParens:
    enabled: false

  TrailingSemicolon:
    enabled: false

  UnnecessaryMantissa:
    enabled: false

  UnnecessaryParentReference:
    enabled: false

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: false

  VendorPrefixes:
    enabled: false

  ZeroUnit:
    enabled: false


# Default Config
# Use for reference
# 
# linters:
#   BangFormat:
#     enabled: true
#     space_before_bang: true
#     space_after_bang: false

#   BorderZero:
#     enabled: true

#   ColorKeyword:
#     enabled: true

#   Comment:
#     enabled: true

#   DebugStatement:
#     enabled: true

#   DeclarationOrder:
#     enabled: true

  # DuplicateProperty:
  #   enabled: true

#   ElsePlacement:
#     enabled: true
#     style: same_line # or 'new_line'

#   EmptyLineBetweenBlocks:
#     enabled: true
#     ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

#   FinalNewline:
#     enabled: false
#     present: false

#   HexLength:
#     enabled: true
#     style: short # or 'long'

#   HexNotation:
#     enabled: true
#     style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

#   IdWithExtraneousSelector:
#     enabled: true
  
  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    allow_non_nested_indentation: false
    enabled: true
    character: tab
    width: 1

#   LeadingZero:
#     enabled: true
#     style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 4

  PlaceholderInExtend:
    enabled: true

#  PropertySortOrder:
#    enabled: true
#    ignore_unspecified: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

#   SelectorDepth:
#     enabled: true
#     max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or 'snake_case', or 'camel_case', or a regex pattern

#   Shorthand:
#     enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

#   SpaceAfterComma:
#     enabled: true

#   SpaceAfterPropertyColon:
#     enabled: true
#     style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

#   SpaceAfterPropertyName:
#     enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

#   SpaceBetweenParens:
#     enabled: true
#     spaces: 0

#   StringQuotes:
#     enabled: true
#     style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

#   UrlFormat:
#     enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - color
      - font

#   VendorPrefixes:
#     enabled: true
#     identifier_list: base
#     include: []
#     exclude: []

  ZeroUnit:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/compass/README.md
  Compass::*:
    enabled: true
